### ISSUE TITLE
Adding Custom Cursor effect

### ISSUE THREAD

**Issue by ShrishtiSingh26** [Mohit5Upadhyay/WeatherApplication#101]
### Unique cursor designs can capture users' attention and make the interaction, encouraging them to engage more with your content.

Please assign this to me , I am ready for this under Hacktoberfest and GSSOC extd
Thankyou!

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan
