### ISSUE TITLE
The logo is not clickable 

### ISSUE THREAD

**Issue by HimangshuSharma01** [Mohit5Upadhyay/WeatherApplication#171]
the logo must be responsive to refresh or reload the web page

https://github.com/user-attachments/assets/b6585372-bb87-435e-948d-1b049457e419

**Comment by rajatsingh535** [comment]
i would like to work on this project. Please assign it to me

**Comment by Adinath-j** [comment]
I am not assigned for the project but I have identified and fixed the issue #171. As part of my open-source contribution, I have made a pull request on your project's GitHub repository for your review. Please assign me.

Here are the details:

Issue: #171
Pull Request: (https://github.com/Mohit5Upadhyay/WeatherApplication/pull/174#issue-2582908541)
