### ISSUE TITLE
 Improve Footer Section by Condensing Content into a Single Line

### ISSUE THREAD

**Issue by prashikk** [Mohit5Upadhyay/WeatherApplication#61]
Issue Description: Currently, the footer section of the Weather Application displays content that could be condensed into a single line for better visual appeal and usability. Here's how we can improve it:

Current Footer Layout: The footer spans multiple lines, which could create unnecessary vertical space and affect the overall layout consistency.

Proposed Improvement: By consolidating the footer content into a single line, we can achieve a cleaner and more compact design without sacrificing information. 

screenshot- 
<img width="1381" alt="Screenshot 2024-10-03 at 3 52 08 PM" src="https://github.com/user-attachments/assets/f1b817be-65ec-461d-b783-047722ef0cff">

This enhancement aims to enhance user experience by optimizing space utilization and maintaining a streamlined visual appearance.

**Comment by AntaraA7953** [comment]
I know HTML , CSS and JavaScript.
I would like to resolve this issue .

HTML Structure: To align text in a single line 
CSS for Styling: To add more style
**The formatted version**
![Screenshot 2024-10-03 223205](https://github.com/user-attachments/assets/c08ee76a-c7b9-42ac-950d-0ba9562dc4c2)
